package Card;


import java.util.Locale;

public class CartReader{
    public CartReader(){
        run();
    }
    private void run() {
        new MonsterCard("Battle OX", "A monster with tremendous power, it destroys enemies with a swing of its axe.", 2900, 4, "Normal", 1700, 1000, MonsterType.valueOf("BEAST_WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Axe Raider", "An axe-wielding monster of tremendous strength and agility.", 3100, 4, "Normal", 1700, 1150, MonsterType.valueOf("WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Yomi Ship", "If this card is destroyed by battle and sent to the GY: Destroy the monster that destroyed this card.", 1700, 3, "Effect", 800, 1400, MonsterType.valueOf("AQUA".toUpperCase(Locale.ROOT)), Attribute.valueOf("WATER".toUpperCase(Locale.ROOT)));
        new MonsterCard("Horn Imp", "A small fiend that dwells in the dark, its single horn makes it a formidable opponent.", 2500, 4, "Normal", 1300, 1000, MonsterType.valueOf("Fiend".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Silver Fang", "A snow wolf that's beautiful to the eye, but absolutely vicious in battle.", 1700, 3, "Normal", 1200, 800, MonsterType.valueOf("Beast".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Suijin", "During damage calculation in your opponent's turn, if this card is being attacked: You can target the attacking monster; make that target's ATK 0 during damage calculation only (this is a Quick Effect). This effect can only be used once while this card is face-up on the field.", 8700, 7, "Effect", 2500, 2400, MonsterType.valueOf("AQUA".toUpperCase(Locale.ROOT)), Attribute.valueOf("WATER".toUpperCase(Locale.ROOT)));
        new MonsterCard("Fireyarou", "A malevolent creature wrapped in flames that attacks enemies with intense fire.", 2500, 4, "Normal", 1300, 1000, MonsterType.valueOf("Pyro".toUpperCase(Locale.ROOT)), Attribute.valueOf("FIRE".toUpperCase(Locale.ROOT)));
        new MonsterCard("Curtain of the dark ones", "A curtain that a spellcaster made, it is said to raise a dark power.", 700, 2, "Normal", 600, 500, MonsterType.valueOf("Spellcaster".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Feral Imp", "A playful little fiend that lurks in the dark, waiting to attack an unwary enemy.", 2800, 4, "Normal", 1300, 1400, MonsterType.valueOf("Fiend".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Dark magician", "The ultimate wizard in terms of attack and defense.", 8300, 7, "Normal", 2500, 2100, MonsterType.valueOf("Spellcaster".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Wattkid", "A creature that electrocutes opponents with bolts of lightning.", 1300, 3, "Normal", 1000, 500, MonsterType.valueOf("Thunder".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT"));
        new MonsterCard("Baby dragon", "Much more than just a child, this dragon is gifted with untapped power.", 1600, 3, "Normal", 1200, 700, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("WIND"));
        new MonsterCard("Hero of the east", "Feel da strength ah dis sword-swinging samurai from da Far East.", 1700, 3, "Normal", 1100, 1000, MonsterType.valueOf("WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH"));
        new MonsterCard("Battle warrior", "A warrior that fights with his bare hands!!!", 1300, 3, "Normal", 700, 1000, MonsterType.valueOf("WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH"));
        new MonsterCard("Crawling dragon", "This weakened dragon can no longer fly, but is still a deadly force to be reckoned with.", 3900, 5, "Normal", 1600, 1400, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH"));
        new MonsterCard("Flame manipulator", "This Spellcaster attacks enemies with fire-related spells such as \"Sea of Flames\" and \"Wall of Fire\".", 1500, 3, "Normal", 900, 1000, MonsterType.valueOf("Spellcaster".toUpperCase(Locale.ROOT)), Attribute.valueOf("FIRE"));
        new MonsterCard("Blue-Eyes white dragon", "This legendary dragon is a powerful engine of destruction. Virtually invincible, very few have faced this awesome creature and lived to tell the tale.", 11300, 8, "Ritual", 3000, 2500, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT"));
        new MonsterCard("Crab Turtle", "This monster can only be Ritual Summoned with the Ritual Spell Card,\"Turtle Oath\". You must also offer monsters whose total Level Stars equal 8 or more as a Tribute from the field or your hand.", 10200, 8, "Ritual", 2550, 2500, MonsterType.valueOf("AQUA".toUpperCase(Locale.ROOT)), Attribute.valueOf("WATER"));
        new MonsterCard("Skull Guardian", "This monster can only be Ritual Summoned with the Ritual Spell Card,\"Novox's Prayer\". You must also offer monsters whose total Level Stars equal 7 or more as a Tribute from the field or your hand.", 7900, 7, "Normal", 2050, 2500, MonsterType.valueOf("WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT"));
        new MonsterCard("Slot Machine", "The machine's ability is said to vary according to its slot results.", 7500, 7, "Normal", 2000, 2300, MonsterType.valueOf("Machine".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK"));
        new MonsterCard("Haniwa", "An earthen figure that protects the tomb of an ancient ruler.", 600, 2, "Normal", 500, 500, MonsterType.valueOf("Rock".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH"));
        new MonsterCard("Man-Eater Bug", "FLIP: Target 1 monster on the field; destroy that target.", 300, 2, "Effect", 450, 600, MonsterType.valueOf("Insect".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH"));
        new MonsterCard("Gate Guardian", "Cannot be Normal Summoned/Set. Must first be Special Summoned (from your hand) by Tributing 1 \"Sanga of the Thunder\",\"Kazejin\", and \"Suijin\".", 20000, 11, "Effect", 3750, 3400, MonsterType.valueOf("WARRIOR".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK"));
        new MonsterCard("Scanner", "Once per turn, you can select 1 of your opponent's monsters that is removed from play. Until the End Phase, this card's name is treated as the selected monster's name, and this card has the same Attribute, Level, ATK, and DEF as the selected monster. If this card is removed from the field while this effect is applied, remove it from play.", 8000, 1, "Effect", 0, 0, MonsterType.valueOf("Machine".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Bitron", "A new species found in electronic space. There's not much information on it.", 1000, 2, "Normal", 200, 2000, MonsterType.valueOf("Cyberse".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Marshmallon", "Cannot be destroyed by battle. After damage calculation, if this card was attacked, and was face-down at the start of the Damage Step: The attacking player takes 1000 damage.", 700, 3, "Effect", 300, 500, MonsterType.valueOf("Fairy".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Beast King Barbaros", "You can Normal Summon/Set this card without Tributing, but its original ATK becomes 1900. You can Tribute 3 monsters to Tribute Summon (but not Set) this card. If Summoned this way: Destroy all cards your opponent controls.", 9200, 8, "Effect", 3000, 1200, MonsterType.valueOf("Beast-Warrior".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Texchanger", "Once per turn, when your monster is targeted for an attack: You can negate that attack, then Special Summon 1 Cyberse Normal Monster from your hand, Deck, or GY.", 200, 1, "Effect", 100, 100, MonsterType.valueOf("Cyberse".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Leotron", "A territorial electronic monster that guards its own domain.", 2500, 4, "Normal", 2000, 0, MonsterType.valueOf("Cyberse".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("The Calculator", "The ATK of this card is the combined Levels of all face-up monsters you control x 300.", 8000, 5, "Effect", 0, 0, MonsterType.valueOf("Thunder".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Alexandrite Dragon", "Many of the czars' lost jewels can be found in the scales of this priceless dragon. Its creator remains a mystery, along with how they acquired the imperial treasures. But whosoever finds this dragon has hit the jackpot... whether they know it or not.", 2600, 4, "Normal",2000 , 100, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Mirage Dragon", "Your opponent cannot activate Trap Cards during the Battle Phase.", 2500, 4, "Effect", 1600, 600, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Herald of Creation", "Once per turn: You can discard 1 card, then target 1 Level 7 or higher monster in your Graveyard; add that target to your hand.", 2700, 4, "Effect", 1800,  600, MonsterType.valueOf("Spellcaster".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Exploder Dragon", "If this card is destroyed by battle and sent to the Graveyard: Destroy the monster that destroyed it. Neither player takes any battle damage from attacks involving this attacking card.", 1000, 3, "Effect", 1000, 0, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Warrior Dai Grepher", "The warrior who can manipulate dragons. Nobody knows his mysterious past.", 3400, 4, "Normal", 1700, 1600, MonsterType.valueOf("Warrior".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("Dark Blade", "They say he is a dragon-manipulating warrior from the dark world. His attack is tremendous, using his great swords with vicious power.", 3500, 4, "Normal", 1800, 1500, MonsterType.valueOf("Warrior".toUpperCase(Locale.ROOT)), Attribute.valueOf("DARK".toUpperCase(Locale.ROOT)));
        new MonsterCard("Wattaildragon", "Capable of indefinite flight. Attacks by wrapping its body with electricity and ramming into opponents. IMPORTANT: Capturing the \"Wattaildragon\" is forbidden by the Ancient Rules and is a Level 6 offense, the minimum sentence for which is imprisonment for no less than 2500 heliocycles.", 5800, 6, "Normal", 2500, 1000, MonsterType.valueOf("Dragon".toUpperCase(Locale.ROOT)), Attribute.valueOf("LIGHT".toUpperCase(Locale.ROOT)));
        new MonsterCard("Terratiger, the Empowered Warrior", "When this card is Normal Summoned: You can Special Summon 1 Level 4 or lower Normal Monster from your hand in Defense Position.", 3200, 4, "Effect", 1800, 1200, MonsterType.valueOf("Warrior".toUpperCase(Locale.ROOT)), Attribute.valueOf("EARTH".toUpperCase(Locale.ROOT)));
        new MonsterCard("The Tricky", "You can Special Summon this card (from your hand) by discarding 1 card.", 4300, 5, "Efect", 2000, 1200, MonsterType.valueOf("Spellcaster".toUpperCase(Locale.ROOT)), Attribute.valueOf("WIND".toUpperCase(Locale.ROOT)));
        new MonsterCard("Spiral Serpent", "When huge whirlpools lay cities asunder, it is the hunger of this sea serpent at work. No one has ever escaped its dreaded Spiral Wave to accurately describe the terror they experienced.", 11700, 8, "Normal", 2900, 2900, MonsterType.valueOf("Sea Serpent".toUpperCase(Locale.ROOT)), Attribute.valueOf("WATER".toUpperCase(Locale.ROOT)));
        new MonsterCard("Command Knight", "All Warrior-Type monsters you control gain 400 ATK. If you control another monster, monsters your opponent controls cannot target this card for an attack.", 2100, 4, "Effect", 1000, 1000, MonsterType.valueOf("Warrior".toUpperCase(Locale.ROOT)), Attribute.valueOf("FIRE".toUpperCase(Locale.ROOT)));
    }

}
